---
# Calamares settings for Atlas OS
modules-search: [ local, /usr/lib/calamares/modules ]

instances:

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - grubcfg
      - initramfscfg
      - initramfs
      - umount
  - show:
      - finished

branding: atlas
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-finished-banner: false
