#!/usr/bin/env bash
# Internet-connected lock refresh: resolve digests into sources.lock.yaml
set -euo pipefail

RELEASE="${1:?release dir}"
CACHE="${2:?cache dir}"
CATALOG="$RELEASE/sources.catalog.yaml"
LOCK="$RELEASE/sources.lock.yaml"
mkdir -p "$CACHE"/{oci,source,ollama,models,licences,sbom}

if ! command -v python3 >/dev/null; then
  echo "python3 required" >&2
  exit 1
fi

python3 - "$CATALOG" "$LOCK" "$CACHE" <<'PY'
import datetime as dt
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

catalog, lock_path, cache = map(Path, sys.argv[1:])
text = catalog.read_text(encoding="utf-8")
assets = []

images = [
    "mysql:8.0",
    "redis:7-alpine",
    "amir20/dozzle:v10.0",
    "ghcr.io/kiwix/kiwix-serve:3.8.2",
    "qdrant/qdrant:v1.16",
    "treehouses/kolibri:0.12.8",
    "ghcr.io/gchq/cyberchef:10.24",
    "dullage/flatnotes:v5.5.4",
    "ollama/ollama:0.24.0",
    "ghcr.io/crosstalk-solutions/project-nomad:v1.33.0",
]

def skopeo_digest(ref: str):
    if not shutil_which("skopeo"):
        return None
    try:
        out = subprocess.check_output(
            ["skopeo", "inspect", f"docker://{ref}"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        data = json.loads(out)
        return data.get("Digest")
    except Exception:
        return None

def shutil_which(cmd):
    from shutil import which
    return which(cmd)

for ref in images:
    digest = skopeo_digest(ref)
    assets.append({
        "type": "oci",
        "ref": ref,
        "digest": digest,
        "status": "resolved" if digest else "pending_network",
    })
    if digest and shutil_which("skopeo"):
        safe = ref.replace("/", "_").replace(":", "_")
        dest = cache / "oci" / f"{safe}.tar"
        if not dest.exists():
            try:
                subprocess.check_call([
                    "skopeo", "copy", f"docker://{ref}", f"oci-archive:{dest}:{safe}"
                ])
            except Exception as e:
                assets[-1]["copy_error"] = str(e)

# Ollama host archive from catalog pins
ollama = {
    "type": "file",
    "id": "ollama-linux-amd64",
    "version": "0.31.2",
    "url": "https://github.com/ollama/ollama/releases/download/v0.31.2/ollama-linux-amd64.tar.zst",
    "sha256": "2c88f0f31a959bac5a3cad4cc5296ec568551d4aa79f548f554adb2b575b3133",
}
assets.append(ollama)

# NOMAD source
assets.append({
    "type": "source",
    "id": "project-nomad",
    "version": "v1.33.0",
    "url": "https://github.com/Crosstalk-Solutions/project-nomad/archive/refs/tags/v1.33.0.tar.gz",
    "commit": None,
})

lock = {
    "schema": "atlas.sources.lock/v1",
    "atlas_version": "0.1.0-alpha",
    "locked_at": dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
    "status": "development" if any(a.get("digest") is None and a.get("type")=="oci" for a in assets) else "locked",
    "assets": assets,
}

# Write YAML-ish via JSON for simplicity + yaml header
import json as _json
body = _json.dumps(lock, indent=2)
lock_path.write_text(
    "# Generated by scripts/lock-refresh.sh — review before release\n"
    + "schema: atlas.sources.lock/v1\n"
    + f"atlas_version: \"0.1.0-alpha\"\n"
    + f"locked_at: \"{lock['locked_at']}\"\n"
    + f"status: {lock['status']}\n"
    + "assets_json: |\n"
    + "\n".join("  " + line for line in _json.dumps(assets, indent=2).splitlines())
    + "\n",
    encoding="utf-8",
)
print(f"Wrote {lock_path} status={lock['status']} assets={len(assets)}")
PY
