---
# Calamares partition recommendations for Atlas OS
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
userSwapChoices: [ none, small, suspend ]
swapPartitionSize: 0
drawNestedPartitions: true
alwaysShowPartitionLabels: true
defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs","ext4","xfs"]
# Installer UI should present LUKS encryption as recommended default via partition module flags
allowZfsEncryption: false
initialPartitioningChoice: always-ask
initialSwapChoice: none
